### ISSUE TITLE
NoiseTorch starts working only if i select as default the "normal" microphone

### ISSUE THREAD

**Issue by Razer0123** [lawl/NoiseTorch#197] opened 2021-11-15 17:50 UTC
I have latest version, autostart is working, but Noisetorch does not actually work if i do not select the normal microphone as default first

When i switch back it starts working, any idea why this happens?

Would love to post some logs, not sure how

**Comment by lawl** [comment] 2021-11-17 02:02
checked https://github.com/lawl/NoiseTorch/wiki/Troubleshooting ?

**Comment by Razer0123** [comment] 2021-11-17 12:25
Yes, this is the message i am getting

`[xgbutil] xgbutil.go:270: WARNING: No extension named XINERAMA could be found on on the server.
[xgbutil] xgbutil.go:271: MESSAGE: The 'xinerama' package cannot be used because the XINERAMA extension could not be loaded.`

Starting Noisetorch does not work, but if i switch to the default mic, then switch back to Noisetorch mic it works

**Comment by lawl** [comment] 2021-11-17 14:52
this error message doesn't seem relevant. please check the wiki page again for how to attach a log.

**Comment by Razer0123** [comment] 2021-11-17 16:30
> this error message doesn't seem relevant. please check the wiki page again for how to attach a log.

`2021/11/17 17:28:53 Application starting. Version: 0.11.4 (archlinux)
2021/11/17 17:28:53 CAP_SYS_RESOURCE: true
2021/11/17 17:28:53 Checking if config needs to be initialized
2021/11/17 17:28:53 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/alessandro/.config'
2021/11/17 17:28:53 Wrote temp librnnoise to: /tmp/librnnoise-3496356542.so
2021/11/17 17:28:53 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/alessandro/.config'
2021/11/17 17:28:53 Audioserver package name: PulseAudio (on PipeWire 0.3.40)
2021/11/17 17:28:53 Audioserver package version: 15.0.0
2021/11/17 17:28:53 Detected PipeWire
2021/11/17 17:28:53 Getting caps for: /usr/bin/noisetorch
2021/11/17 17:28:53 Audioserver package name: PulseAudio (on PipeWire 0.3.40)
2021/11/17 17:28:53 Audioserver package version: 15.0.0
2021/11/17 17:28:53 Detected PipeWire
2021/11/17 17:28:53 Connected to audio server. Server name 'PipeWire'
2021/11/17 17:28:53 Output alsa_output.pci-0000_08_00.1.hdmi-stereo-extra2, {Index:47 Name:alsa_output.pci-0000_08_00.1.hdmi-stereo-extra2 Description:GA104 High Definition Audio Controller Digital Stereo (HDMI 3) SampleSpec:{Format:3 Channels:2 Rate:48000} ChannelMap:[1 2] ModuleIndex:4294967295 Cvolume:[48287 48287] Muted:false MonitorSourceIndex:65583 MonitorSourceName:alsa_output.pci-0000_08_00.1.hdmi-stereo-extra2.monitor Latency:0 Driver:PipeWire Flags:422 PropList:map[alsa.card:1 alsa.card_name:HDA NVidia alsa.class:generic alsa.device:8 alsa.driver_name:snd_hda_intel alsa.id:HDMI 2 alsa.long_card_name:HDA NVidia at 0xfc080000 irq 102 alsa.name:HDMI 2 alsa.resolution_bits:16 alsa.subclass:generic-mix alsa.subdevice:0 alsa.subdevice_name:subdevice #0 api.alsa.path:hdmi:1,2 api.alsa.pcm.card:1 api.alsa.pcm.stream:playback audio.adapt.follower: audio.channels:2 audio.position:FL,FR card.profile.device:13 client.id:32 device.api:alsa device.bus:pci device.bus_path:pci-0000:08:00.1 device.class:sound device.description:GA104 High Definition Audio Controller Digital Stereo (HDMI 3) device.icon_name:audio-card-hdmi device.id:41 device.profile.description:Digital Stereo (HDMI 3) device.profile.name:hdmi-stereo-extra2 device.routes:1 factory.id:18 factory.mode:merge factory.name:api.alsa.pcm.sink library.name:audioconvert/libspa-audioconvert media.class:Audio/Sink node.driver:true node.name:alsa_output.pci-0000_08_00.1.hdmi-stereo-extra2 node.nick:HDA NVidia node.pause-on-idle:false object.id:47 object.path:alsa:pcm:1:hdmi:1,2:playback priority.driver:552 priority.session:552] RequestedLatency:0 BaseVolume:65536 SinkState:2 NVolumeSteps:0 CardIndex:41 Ports:[{Name:hdmi-output-2 Description:HDMI / DisplayPort 3 Pririty:5700 Available:2}] ActivePortName:hdmi-output-2 Formats:[{Encoding:1 PropList:map[]}]}
2021/11/17 17:28:53 Output alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo, {Index:48 Name:alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo Description:Audio Adapter (Unitek Y-247A) Stereo analogico SampleSpec:{Format:3 Channels:2 Rate:48000} ChannelMap:[1 2] ModuleIndex:4294967295 Cvolume:[33113 33113] Muted:false MonitorSourceIndex:65584 MonitorSourceName:alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo.monitor Latency:0 Driver:PipeWire Flags:183 PropList:map[alsa.card:0 alsa.card_name:USB Audio Device alsa.class:generic alsa.device:0 alsa.driver_name:snd_usb_audio alsa.id:USB Audio alsa.long_card_name:C-Media Electronics Inc. USB Audio Device at usb-0000:0c:00.3-2, full speed alsa.name:USB Audio alsa.resolution_bits:16 alsa.subclass:generic-mix alsa.subdevice:0 alsa.subdevice_name:subdevice #0 api.alsa.path:front:0 api.alsa.pcm.card:0 api.alsa.pcm.stream:playback audio.adapt.follower: audio.channels:2 audio.position:FL,FR card.profile.device:3 client.id:32 device.api:alsa device.bus:usb device.bus_path:pci-0000:0c:00.3-usb-0:2:1.0 device.class:sound device.description:Audio Adapter (Unitek Y-247A) Stereo analogico device.icon_name:audio-card-analog device.id:44 device.profile.description:Stereo analogico device.profile.name:analog-stereo device.routes:1 factory.id:18 factory.mode:merge factory.name:api.alsa.pcm.sink library.name:audioconvert/libspa-audioconvert media.class:Audio/Sink node.driver:true node.name:alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo node.nick:USB Audio Device node.pause-on-idle:false object.id:48 object.path:alsa:pcm:0:front:0:playback priority.driver:1009 priority.session:1009] RequestedLatency:0 BaseVolume:65536 SinkState:2 NVolumeSteps:0 CardIndex:44 Ports:[{Name:analog-output-speaker Description:Altoparlanti Pririty:10000 Available:0}] ActivePortName:analog-output-speaker Formats:[{Encoding:1 PropList:map[]}]}
2021/11/17 17:28:53 Output alsa_output.pci-0000_0c_00.4.analog-stereo, {Index:50 Name:alsa_output.pci-0000_0c_00.4.analog-stereo Description:Starship/Matisse HD Audio Controller Stereo analogico SampleSpec:{Format:7 Channels:2 Rate:48000} ChannelMap:[1 2] ModuleIndex:4294967295 Cvolume:[37025 37025] Muted:false MonitorSourceIndex:65586 MonitorSourceName:alsa_output.pci-0000_0c_00.4.analog-stereo.monitor Latency:0 Driver:PipeWire Flags:183 PropList:map[alsa.card:3 alsa.card_name:HD-Audio Generic alsa.class:generic alsa.device:0 alsa.driver_name:snd_hda_intel alsa.id:ALC1220 Analog alsa.long_card_name:HD-Audio Generic at 0xfc400000 irq 105 alsa.name:ALC1220 Analog alsa.resolution_bits:16 alsa.subclass:generic-mix alsa.subdevice:0 alsa.subdevice_name:subdevice #0 api.alsa.path:front:3 api.alsa.pcm.card:3 api.alsa.pcm.stream:playback audio.adapt.follower: audio.channels:2 audio.position:FL,FR card.profile.device:5 client.id:32 device.api:alsa device.bus:pci device.bus_path:pci-0000:0c:00.4 device.class:sound device.description:Starship/Matisse HD Audio Controller Stereo analogico device.icon_name:audio-card-analog device.id:45 device.profile.description:Stereo analogico device.profile.name:analog-stereo device.routes:2 factory.id:18 factory.mode:merge factory.name:api.alsa.pcm.sink library.name:audioconvert/libspa-audioconvert media.class:Audio/Sink node.driver:true node.max-latency:8192/48000 node.name:alsa_output.pci-0000_0c_00.4.analog-stereo node.nick:HD-Audio Generic node.pause-on-idle:false object.id:50 object.path:alsa:pcm:3:front:3:playback priority.driver:817 priority.session:817] RequestedLatency:0 BaseVolume:65536 SinkState:2 NVolumeSteps:0 CardIndex:45 Ports:[{Name:analog-output-lineout Description:Line-Out Pririty:9000 Available:2} {Name:analog-output-headphones Description:Cuffie analogiche Pririty:9900 Available:1}] ActivePortName:analog-output-lineout Formats:[{Encoding:1 PropList:map[]}]}
2021/11/17 17:28:55 Loading supressor for pipewire
2021/11/17 17:28:55 Loaded ladspa source as idx: 262144
2021/11/17 17:28:55 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/alessandro/.config'
2021/11/17 17:29:43 Unloading modules for pipewire
2021/11/17 17:29:43 Searching for module-ladspa-source
2021/11/17 17:29:43 Found module-ladspa-source at id [262144], sending unload command
2021/11/17 17:29:43 Searching for module-ladspa-sink
2021/11/17 17:29:44 Deleted temp librnnoise: /tmp/librnnoise-3496356542.so`

**Comment by lawl** [comment] 2021-11-18 04:17
Probably a dupe of #168 . PipeWire seems to be so buggy currently on their side, there's not much I can do.

If you need things to work, stop using PipeWire, for now.

**Closed by lawl** 2021-11-18 04:17 UTC
