### ISSUE TITLE
Using two (or more) microphones to supress noise

### ISSUE THREAD

**Issue by rafifos** [lawl/NoiseTorch#109] opened 2021-04-05 17:08 UTC
Many mobile devices (like Android smartphones) have two, three or even more audio input sources (aka microphones) to help them deal with background noise.

I haven't found any existing software for PC that does the same (for example, using my Webcam microphone as an additional audio input to supress noise coming from both it and my condenser microphone). There seems to be some papers explaining it, but I'm not sure why nobody does it on PC. Maybe I'm missing something here. Is it even possible on PC (and if `true`, it's something that NoiseTorch should implement, or it should be on PulseAudio itself like the echo cancellation module?)?

**Comment by lawl** [comment] 2021-04-05 17:10
Duplicate of #68

**Closed by lawl** 2021-04-05 17:10 UTC
Labels: duplicate
