### ISSUE TITLE
Option to use it as default source

### ISSUE THREAD

**Issue by Edu4rdSHL** [lawl/NoiseTorch#150] opened 2021-06-13 08:32 UTC
Hello, first of all, thank you for this awesome job! I don't know if it's a bug or intentional, once NoiseTorch creates the input device and I select it as default in pavucontrol no input is processed anymore, the behavior was explained in https://github.com/lawl/NoiseTorch/issues/134#issuecomment-860001912 but as the point of that issue is a different one I'm opening this bug. Steps to reproduce:

- Load NoiseTorch.
- Make the NoiseTorch Microphone the default input device.
- Input Audio should stop working now.

Anyways, simply loading NoiseTorch and then selecting the device as input works as expected (tested on Discord) but not all applications let you select the input device (Telegram desktop, for example) so, it would be very good to be able to select it as default input device globally.

Edit:

I forgot to mention that I'm currently using Pipewire instead of Pulseaudio.

Regards,
Ed

**Comment by lawl** [comment] 2021-06-13 20:04
duplicate of #79 

You can force the nosietorch microphone on apps without settings with `pavucontrol` in the meantime.

**Closed by lawl** 2021-06-13 20:04 UTC
