### ISSUE TITLE
Cannot open normally on Solus

### ISSUE THREAD

**Issue by Khrona98** [lawl/NoiseTorch#36] opened 2020-07-22 20:05 UTC
Hello there!
I'm currently experiencing a few issues on Solus, primarily not being able to open NoiseTorch:

- After installation I can't open the program normally, even after adding the `PATH` to `~/.profile`. The program won't show in Budgie Application Menu. It does, however, show on Albert, but won't open. The only way I can open it is by putting the `PATH` on my `~/.zshrc` file and open it through the terminal by typing `noisetorch`.

- Opening through the terminal works fine, but when loading the denoised mic, it requires sudo. From what I saw there is already an issue for that, but I thought of mentioning it here just in case. After clicking `cancel` it actually succeeds and seems to work without issues from the little I tested on OBS.

- Also, when loading/reloading, there seems to be a small chance that I can hear myself through my headset when talking. It doesn't happen all the time, but is a bit annoying. Unfortunately, I couldn't reliably reproduce it to happen consistently, looks to happen randomly when activating the denoised mic.

- The last issue I'm facing is that the newly created audio sources appear on the Raven Sidebar on the Budgie DE as you can see on the screenshot below. It is not a big deal by any means, but is kind of annoying and contributes to visual clutter there, if there is a way to hide it from view it would be great.

### Audio sources:

![Screenshot from 2020-07-22 16-13-42](https://user-images.githubusercontent.com/9277125/88220882-00188d80-cc3a-11ea-83a4-86dc30720e4c.png) 

### Full Raven sidebar for reference:

![Screenshot from 2020-07-22 16-43-42](https://user-images.githubusercontent.com/9277125/88222842-f0e70f00-cc3c-11ea-9405-dd02f42b6054.png)

If you prefer to have these different problems on separate github issues for easy of tracking, please let me know and I'll create other issues for each one.

Nonetheless, thanks for the effort in making this application, it is extremely useful and I appreciate it.

**Comment by lawl** [comment] 2020-07-22 20:18
Hey

* Unfortunately I do not know what solus is or any of the other applications you mentioned like Budgie or Albert. Where does your DE look for  `.desktop` files?

* Yes it prompts for root, and *may* work without for *some* people, for the reason, see this explanation I wrote a few hours ago: https://github.com/lawl/NoiseTorch/issues/33#issuecomment-662566283

* If this *only* happens during loading and not afterwards, I've sometimes noticed that too, but there's likely nothing I can do about that.

* These additional sources are unfortunately required as that's currently the only way to make a virtual microphone work with PulseAudio, nothing I can do about that until PulseAudio gets support for microphone filters.

**Comment by Khrona98** [comment] 2020-07-22 20:55
Sorry, I should have specified these things.

## Explanation:
Solus is an independent distro, it is not based on any other distro like Ubuntu is on Debian and Manjaro is on Arch. In case you want to check it out: [Solus](https://getsol.us/home/)

It's main/default DE is called Budgie (it is made by the same people behind Solus) and it is also available for Ubuntu and Manjaro.

Raven is one of the applets that come with Budgie by default, it is this sidebar in the screenshot with a calendar, notifications, volume and media controls.

Albert is simply a launcher, similar to Spotlight that, I believe, comes by default on Mac OS computers. From what I know, Albert is available in almost any other distro.
##

- I'm not sure, but I think it would be the same as other distros, as my home folder is populated with some `.desktop `files. The `.profile` one mentioned in the `README` was already there too, I just modified it by putting the `PATH` in there but it didn't work unfortunately.

- Thank you for the link, I haven't read it before. I was a little confused before because the original thread on the prompt for root was pointing out that it only asked for it on a secondary user, and as I only have one that is an administrator I thought it could just be a bug or some other issue.

- Sorry I wasn't clear on this issue, what I meant was that it persisted after the loading of the denoised mic. After unloading it and loading again it worked fine. This also happened at least once when I was trying Cadmus a few days ago, maybe it could be a Pulseaudio issue?

- Got it. Would there be any way to simply hide these sources from view? It's not a big deal by any means, but at least would make it cleaner on Raven if it is possible.

**Comment by lawl** [comment] 2020-07-22 21:24
* The search path for `.desktop` files has nothing to do with the `PATH`, as you said you can type "noisetorch" in a terminal and it works, your PATH is fine, the issue is Budgie apparently not finding the desktop icon, it currently places it in

    ~/.local/share/icons/hicolor/256x256/apps/noisetorch.png 

where other DE's seem to find it. I don't know in what paths Budgie looks either, you'd have to figure it out, and copy that file over there.

* I've added it to the wiki now, hopefully people can find it better that way.

* Very weird, no idea what that could be at the moment, since we always load modules the exact same way, it does sound like a pulse issue, but I've never experienced that. I'd be very interested if you could find a way to reproduce this. Or if it happens run the following three commands and throw me the output in [gists](https://gist.github.com/). 

    pacmd list-sources
    pacmd list-modules
    pacmd list-sinks

Please create a new issue then.

* As far as I'm aware, not anything I can do in NoiseTorch. For the question if you're applet can hide it, I don't know, you need to ask the makers of the applet.

**Comment by Khrona98** [comment] 2020-07-22 22:38
Oh sorry, I misinterpreted the `.desktop` files with dot files in general. Budgie looks for the same place for .`desktop` files in `~/.local/share/applications` as other DE's.

- After searching a bit and trying a few things I found that adding the `PATH` to `.profile` is irrelevant on Solus. The correct way to do it here is to create the folder `profile.d` inside `/etc` and then create a script inside `/etc/profile.d` with this:
```
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
```
In my case I named the script 10-path.sh but I think it can be named anything as long as it has a number and a hyphen before the `name.sh`.

After that I'm now able to start NoiseTorch normally from both the Budgie Menu and Albert.

- If I encounter the problem again I'll make another issue with the outputs of the commands you provided, thanks.

- Ok, thanks, I'll try to ask the Solus devs if they could include NoiseTorch in the Solus Repos and ask about the sources appearing on Raven.

**Comment by lawl** [comment] 2020-07-23 12:55
>  Solus have a dev channel that let users ask for package inclusions, would it be ok for you if I ask them to include NoiseTorch in the Solus repos?

Generally yes, in practice NoiseTorch [currently lacks a way to disable the self updater at compile time](https://github.com/lawl/NoiseTorch/issues/2#issuecomment-660662103), which is something distro packages probably want.

**Comment by lawl** [comment] 2020-07-24 11:52
Could you close this issue if you think all your questions have been answered?

**Comment by lawl** [comment] 2020-07-25 12:45
Closing this. Please reopen if you feel a question wasn't answered.

**Closed by lawl** 2020-07-25 12:45 UTC
Labels: question

**Comment by Khrona98** [comment] 2020-07-31 20:41
Sorry for the late response, I couldn't get to it before.

One last thing: could you please add the information about how to set the PATH variable in Solus that I provided to the README or Wiki? This way other users that face the same issue can easily found how to solve it.
