### ISSUE TITLE
NoiseTorch causes "RTC Connecting" issue when connecting to Discord voice rooms

### ISSUE THREAD

**Issue by Proventius** [lawl/NoiseTorch#192] opened 2021-11-01 23:15 UTC
This issue only happens when NoiseTorch is loaded and you try to connect to a Discord Call or Voice room. You will not be able to fully join the voice session until you unload NoiseTorch and then reset it as your microphone input.

![2021-11-01_19-13](https://user-images.githubusercontent.com/67876414/139754100-a8f8ab96-3e8a-4f4f-8f61-57d395a06cdf.png)

**Comment by ConstBur** [comment] 2021-11-02 14:28
I have the same issue occurring with PipeWire and WirePlumber setup.

**Comment by lawl** [comment] 2021-11-04 07:06
Does discord work in when used in chrome(ium)? Might this be a general electron problem? (i think the ones you listed are all electron)

**Comment by Mark42XLII** [comment] 2021-11-05 16:54
Same here, but similarly to #181, this isn't really a NoiseTorch problem.
If you follow [this](https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Filter-Chain#rnnoise-example) guide on the PipeWire wiki and simply load the filter directly on PipeWire through a configuration file, the exact same thing happens.
A workaround I've found is connecting the output of the filter chain to the input of a virtual source and using that virtual source on applications. That way the issue goes away, so there's definitively something wrong with how `libpipewire-module-filter-chain` interacts with some PulseAudio clients.

**Comment by ConstBur** [comment] 2021-11-05 17:12
> Does discord work in when used in chrom(e/ium)? Might this be a general electron problem? (i think the ones you listed are all electron)

It does work in Chromium just fine, might be an Electron problem. Afaik Zoom isn't using it but hey anything can happen in that trash program :) 

@Mark42XLII I'm not using Fedora, but Garuda (based on Arch) recently migrated to WirePlumber just like Fedora between 34 and 35, so maybe the problem lies there. I didn't have this issue with whatever the previous PipeWire session manager was (I think it was ```pipewire-media-session```).

**Comment by joaodefelipe** [comment] 2021-11-05 19:20
@ConstBur I run Debian Testing, and I recall this happening way before bullseye turned stable. I just got wireplumber replacing pipewire-media-session about a week ago.

**Comment by Mark42XLII** [comment] 2021-11-06 01:21
@ConstBur I use Debian bookworm, and I'm positive this happened before `pipewire-media-session` was phased out.

**Comment by sull324** [comment] 2021-11-08 03:37
having the same issues,seem to goes away after reloading multiple time.not sure what is the cause. only happen after an reboot.

**Comment by raaffaaeell** [comment] 2021-11-10 03:04
> A workaround I've found is connecting the output of the filter chain to the input of a virtual source and using that virtual source on applications. 

How do I do this ?

**Comment by sull324** [comment] 2021-11-10 03:06
yes in would like to know,.

**Comment by sull324** [comment] 2021-11-10 03:08
i mean what command line you used,im pretty new to pulse and pipewire an
example would help me greatly ,thank you.

**Comment by Mark42XLII** [comment] 2021-11-10 09:12
Firsty, I followed [werman's instructions](https://github.com/werman/noise-suppression-for-voice#pipewire) for using it with PipeWire and the tutorial on PipeWire's wiki for [loading a virtual source](https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Virtual-Devices#create-a-source), and hooked up the output of the filter chain containing RNNoise to the input of the virtual source using QjackCtl's patch bay feature. You can also use `pw-link`as the wiki instructs. One thing it doesn't mention is that you might want to set `audio.position = [ FL FR ]` under `libpipewire-module-filter-chain`'s `args`, so that the channels have the proper names instead of `capture_1` and `capture_2`.

That functioned as a temporary workaround, but after extensive testing, I observed other weird behaviors (not sure if bugs):
- PipeWire completely ignores the `context.objects` section of a configuration file loaded with `pipewire -c filename.conf`, so you'll need to put it on `~/.config/pipewire/pipewire.conf`, where it'll be automatically read by PipeWire upon startup.
- If you accept the previous limitation, you can use [this configuration snippet](https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Virtual-Devices#single-nodes) with `media.class = Audio/Source/Virtual` for creating a virtual source on startup. However, there is no way to control how the nodes get linked (`node.target` seems to have no effect, and this approach connected the output of my virtual source to the input of the RNNoise filter chain). One possible workaround is using [`context.exec`](https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/src/daemon/pipewire.conf.in#L230) with `pw-link`. From [this page](https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Config-pipewire-media-session), it seems to me that linking nodes automatically is the session manager's job, which is an entirely different can of worms.

Finally, I (think) I've managed to find a better solution with doesn't need the virtual source. If you're willing to do some testing, try `pipewire -c` with [this](https://gist.github.com/Mark42XLII/5ab756adfc7dea59e843ee98fa7ded99) gist, **changing the library location to your particular setup**. On my system, not only does this fix Discord's "RTC Connecting" issue, but also the issue described on #181, where selecting the source on Discord causes all applications using PipeWire to "drop" and disconnect from the sound server.

A peculiar behavior I have seen is that if you use this configuration and hit Control+C to kill the process you just created, completely unloading it, it leaves lasting effects on your PipeWire session. After that, both the example on PipeWire's wiki and NoiseTorch start working properly with Discord.

Now, here's some pure speculation on my part as to what could be causing this mess: Discord could be trying to "query" a handle/instance for the source using the string that describes it (or any other ambiguous information shared among the input/output nodes of the filter chain), ultimately grabbing the wrong node and trying to do some impossible thing like reading from a sink, thus crashing the entire daemon. The strange behavior I observed could also be explained by the session manager (pipewire-media-session or WirePlumber) "remembering" (just like how it does for default sources/sinks and device volumes) which node is the actual *source*, even after an unload of the original filter chain. Take this with a rock of salt though, I'm probably missing a lot here. Just leaving this here in case I (or anyone with spare time) come back to this issue on the future, armed with a proper debugger and actual knowledge on how PipeWire works. I still haven't tested if this is an Electron-specific issue. However, if this fix works for everyone, it's very reasonable IMO to implement it in NoiseTorch.

**Comment by sull324** [comment] 2021-11-10 21:31
@Mark42XLII

I used pipewire -c rnnoise-testfix.conf  (your script) without even modifing the file,got an butch of errors(obvious),then did control + C ,then boom. I load noisetorch,then discord and everything work like before. 

Thanks for taking the time to help out :D.

**Comment by Mark42XLII** [comment] 2021-11-10 21:36
@sull324 Would you be able to share the output of the command with the errors you got? Nothing of the sort ever happened on my side...

**Comment by sull324** [comment] 2021-11-10 21:38
@Mark42XLII the errors were caused by not changing the library location and not having the plugins. Like i said i havent edited your script. i Just ran it,control +C. And noisetorch loaded fine after it.

**Comment by sull324** [comment] 2021-11-15 19:19
seem to be solved with the new pipewire update. if anyone else can confirm.

**Comment by raaffaaeell** [comment] 2021-11-16 16:33
It seems to work now, but a bit different from the behaviour with pipewire-media-session. Noisetorch creates and mic, but I have to use the source mic to get some sound. it'll be filtered, but it's strange

**Comment by Mark42XLII** [comment] 2021-11-16 20:47
Not sure when it was fixed for me, but I'm currently on pipewire 0.3.40 and I can confirm the issue has disappeared. Can't say I've noticed anything strange.

**Comment by lawl** [comment] 2021-11-17 02:03
closing this, since it seems to be a (resolved) pipewire issue

**Closed by lawl** 2021-11-17 02:03 UTC
