### ISSUE TITLE
Sudo required on non-admin account

### ISSUE THREAD

**Issue by domsle** [lawl/NoiseTorch#33] opened 2020-07-22 16:19 UTC
Hey,

So I have a machine with two user accounts - one main, the admin, and one strictly for work. I have installed NoiseTorch, the latest version. Running it on admin account does not require me to enter any passwords.

Problem is, running it on non-root work account pop this window:
![image](https://user-images.githubusercontent.com/18559095/88201428-b9ca2b00-cc47-11ea-8f37-77f18d8ff6fa.png)
Is this expected? Is there any workaroud this?

**Comment by lawl** [comment] 2020-07-22 16:51
This is expected and required to work around a problem.

We're in a bit of a weird situation here where you can just click cancel on this root prompt and it *may* work, but root is required to make it work reliably.

The issue is that the pulseaudio process has a set `RLIMIT_RTTIME`, what that means is that the pulseaudio process is running as a real-time process, which it needs to, because it processes audio, so the kernel makes sure it always gets CPU time when it needs it essentially.

The `RLIMIT_RTTIME` now sets a limit on this CPU time pulseaudio can use, if pulseaudio crosses that limit, the Kernel kills the process immediately. The reason for that is that if a real-time process has a bug, say it enters and endless loop without giving the CPU back, your system will freeze up.

This is where the problem arises, when we load our denoising library into the pulseaudio process, pulseaudio is already under these `RLIMIT_RTTIME` constraints, as it has already entered real-time mode. But loading a library includes operations that are usually a no-no for real-time processes, such as mapping the file from disk into memory etc.

So we're in a situation here where what we're doing should be done during pulseaudio start up, but where we also can't really do that, because for example we need to apply [some work-arounds to filter microphone input](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/120) which means NoiseTorch consumes CPU to denoise the microphone even if no application is using it.

Thus the only real option left to us, is to temporarily remove the `RLIMIT_RTTIME` constraint from the process, but increasing/removing this limit requires either root, or the `CAP_SYS_RESOURCE`. If we used `CAP_SYS_RESOURCE` we would only need root during installation, but this is difficult currently because of how installation works, and something that I think would be mostly feasible in packages installed and updated through the distribution's packet manager.

So that's why we prompt for root, to perform exactly this one operation, removing the `RLIMIT_RTTIME` as root, (and after we're done loading immediately reinstating it, which doesn't require root).

I am also not happy about this, but I currently don't see a viable alternative, unfortunately. If your system happens to handle loading within these constraints fine, you can just click cancel on the root prompt, but [there's too many people where it works inconsistently, or never](https://github.com/lawl/NoiseTorch/issues/11).

You can find the code that's executed as root in this [`if` block in main.go](https://github.com/lawl/NoiseTorch/blob/master/main.go#L37) which is spawned from [this function](https://github.com/lawl/NoiseTorch/blob/37b35ce1eed438adee42e50d0cc0ddf48375846e/rlimit.go#L43).

If anyone has a better idea to solve this, please let me know, I'd love to remove this, and I know it seems sketchy that we prompt for root.

**Comment by lawl** [comment] 2020-07-22 17:00
As for work arounds, you could set

    rlimit-rttime = -1

In your pulseaudio config to always run it without and `RTTIME` limit [as described here](https://github.com/lawl/NoiseTorch/issues/11#issuecomment-659849471), but I wouldn't recommend that, if pulse then hangs, your entire system hangs, which is we we currently do it only for exactly as long as neccessary. Or again, you may just be lucky and it may work on your box without root, you can then either just click cancel, or remove the call do to this in the source (we currently don't have a config option for this).

**Comment by domsle** [comment] 2020-07-22 18:47
I also sometimes have the following error:
```
[dominik@swift ~]$ noisetorch 
2020/07/22 20:46:19 error opening file: open /tmp/noisetorch.log: permission denied
```

**Comment by lawl** [comment] 2020-07-22 19:03
i suppose we should append a timestamp to the name, as if you run it first as root, it will be created as root and then your user can't write to it. I'll create an issue to fix this.

**Comment by domsle** [comment] 2020-07-22 19:05
Couldn't this issue (the main one) be solved by setting some kind of system service/daemon? I understand the flexibility of having it installed only in each users' home directory, but maybe this could be somehow done for people wanting it.

**Comment by lawl** [comment] 2020-07-22 19:21
I think the proper way to solve this would be to make sure that the binary has  `CAP_SYS_RESOURCE` so it doesn't need root at all.

This requires a change to how we install NoiseTorch, and I think is something we should eventually do, it's also cleaner than having yet another daemon running.

It's something I'd like to eventually do, but for now shelling out to `pkexec` is the quick and dirty way that works for most people.

You could build from source according to the readme and patch this line in `rlimit.go`

    	cmd := exec.Command("pkexec", self, "-removerlimit", strconv.Itoa(pid))

to

    	cmd := exec.Command(self, "-removerlimit", strconv.Itoa(pid))

 manually execute

    sudo setcap 'CAP_SYS_RESOURCE=+ep' /path/to/executable

Which I haven't tested, but *I think* should work for what you want to do.

**Comment by domsle** [comment] 2020-07-22 19:25
Probably not what you want to do, but it is also possible to add a command to "whitelist" in pkexec like in the link:
https://forum.manjaro.org/t/fix-sudoers-file-nothing-can-use-sudo/32494/7

**Comment by lawl** [comment] 2020-07-22 19:25
Then I suppose that's something you could do on your system too, yes.

**Comment by domsle** [comment] 2020-07-22 19:27
You are absolutely right :)

**Comment by lawl** [comment] 2020-07-22 20:22
If this is resolved, then please close this issue, otherwise I'm happy to answer any questions. Redesigning how we elevate is tracked in #27 so I believe there's nothing more I can do for you right now, short term.

**Closed** 2020-07-22 20:35 UTC
