### ISSUE TITLE
Add support for "Family 17h (Model 10h-1fh) HD Audio Controller"

### ISSUE THREAD

**Issue by git-alex-voronin** [lawl/NoiseTorch#77] opened 2020-12-17 08:44 UTC
Receive "incompatible" warning in app:
![image](https://user-images.githubusercontent.com/13518123/102463712-85bf2e80-405c-11eb-900a-71f4ff0cfe4a.png)

Version: 0.9.0

**Comment by lawl** [comment] 2020-12-17 08:47
If it doesn't work properly, then it'll be a duplicate of #30 or #48 no easy fix unfortunately, and I still don't have any hardware to reproduce these issues, so nothing i can do here, sorry.

**Closed by lawl** 2020-12-17 08:47 UTC

**Comment by git-alex-voronin** [comment] 2020-12-19 21:03
I am also a developer (Java), if you need any logs or I can provide any information about my hardware - please text me if I can help.

In any case, thank you for a good product!

**Comment by Pijuli** [comment] 2020-12-23 14:58
Hey, it's working for me although it says incompatible.
@lawl if you need any information about it just let me know!
![torch](https://user-images.githubusercontent.com/1220004/103009901-beb54280-4537-11eb-9126-2c9746e14cfe.png)

**Comment by lawl** [comment] 2020-12-23 15:06
@Pijuli So you experience no crackling in the microphone output or anything? It's expected that you can load it.

If so, `pacmd list-sources` would be interesting

**Comment by Pijuli** [comment] 2020-12-23 15:17
No crackling nothing over here :) still, a bit boxed sound and feeling like you are a bit far, but no more noises.
There you go. 


`8 source(s) available.
    index: 1
	name: <alsa_output.pci-0000_04_00.6.analog-stereo.monitor>
	driver: <module-alsa-card.c>
	flags: DECIBEL_VOLUME LATENCY 
	state: IDLE
	suspend cause: (none)
	priority: 1030
	volume: front-left: 65536 / 100% / 0,00 dB,   front-right: 65536 / 100% / 0,00 dB
	        balance 0,00
	base volume: 65536 / 100% / 0,00 dB
	volume steps: 65537
	muted: no
	current latency: 0,00 ms
	max rewind: 17 KiB
	sample spec: s16le 2ch 48000Hz
	channel map: front-left,front-right
	             Estèreo
	used by: 0
	linked by: 0
	fixed latency: 100,14 ms
	monitor_of: 1
	card: 1 <alsa_card.pci-0000_04_00.6>
	module: 8
	properties:
		device.description = "Monitor of Family 17h (Models 10h-1fh) HD Audio Controller Estèreo analògic"
		device.class = "monitor"
		alsa.card = "1"
		alsa.card_name = "HD-Audio Generic"
		alsa.long_card_name = "HD-Audio Generic at 0xfe6c0000 irq 87"
		alsa.driver_name = "snd_hda_intel"
		device.bus_path = "pci-0000:04:00.6"
		sysfs.path = "/devices/pci0000:00/0000:00:08.1/0000:04:00.6/sound/card1"
		device.bus = "pci"
		device.vendor.id = "1022"
		device.vendor.name = "Advanced Micro Devices, Inc. [AMD]"
		device.product.id = "15e3"
		device.product.name = "Family 17h (Models 10h-1fh) HD Audio Controller"
		device.string = "1"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-pci"
    index: 2
	name: <alsa_input.pci-0000_04_00.6.analog-stereo>
	driver: <module-alsa-card.c>
	flags: HARDWARE HW_MUTE_CTRL HW_VOLUME_CTRL DECIBEL_VOLUME LATENCY 
	state: RUNNING
	suspend cause: (none)
	priority: 9039
	volume: front-left: 24929 /  38% / -25,19 dB,   front-right: 24929 /  38% / -25,19 dB
	        balance 0,00
	base volume: 6554 /  10% / -60,00 dB
	volume steps: 65537
	muted: no
	current latency: 0,70 ms
	max rewind: 0 KiB
	sample spec: s16le 2ch 48000Hz
	channel map: front-left,front-right
	             Estèreo
	used by: 1
	linked by: 1
	fixed latency: 100,14 ms
	card: 1 <alsa_card.pci-0000_04_00.6>
	module: 8
	properties:
		alsa.resolution_bits = "16"
		device.api = "alsa"
		device.class = "sound"
		alsa.class = "generic"
		alsa.subclass = "generic-mix"
		alsa.name = "ALC269VC Analog"
		alsa.id = "ALC269VC Analog"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		alsa.device = "0"
		alsa.card = "1"
		alsa.card_name = "HD-Audio Generic"
		alsa.long_card_name = "HD-Audio Generic at 0xfe6c0000 irq 87"
		alsa.driver_name = "snd_hda_intel"
		device.bus_path = "pci-0000:04:00.6"
		sysfs.path = "/devices/pci0000:00/0000:00:08.1/0000:04:00.6/sound/card1"
		device.bus = "pci"
		device.vendor.id = "1022"
		device.vendor.name = "Advanced Micro Devices, Inc. [AMD]"
		device.product.id = "15e3"
		device.product.name = "Family 17h (Models 10h-1fh) HD Audio Controller"
		device.string = "front:1"
		device.buffering.buffer_size = "17664"
		device.buffering.fragment_size = "2944"
		device.access_mode = "mmap"
		device.profile.name = "analog-stereo"
		device.profile.description = "Estèreo analògic"
		device.description = "Family 17h (Models 10h-1fh) HD Audio Controller Estèreo analògic"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-pci"
	ports:
		analog-input-internal-mic: Micròfon intern (priority 8900, latency offset 0 usec, available: no)
			properties:
				device.icon_name = "audio-input-microphone"
		analog-input-mic: Micròfon (priority 8700, latency offset 0 usec, available: yes)
			properties:
				device.icon_name = "audio-input-microphone"
	active port: <analog-input-mic>
  * index: 3
	name: <noechosource>
	driver: <module-echo-cancel.c>
	flags: HW_MUTE_CTRL LATENCY 
	state: RUNNING
	suspend cause: (none)
	priority: 1000
	volume: mono: 24929 /  38%
	        balance 0,00
	base volume: 65536 / 100%
	volume steps: 65537
	muted: no
	current latency: 7,34 ms
	max rewind: 0 KiB
	sample spec: float32le 1ch 32000Hz
	channel map: mono
	             Mono
	used by: 2
	linked by: 2
	fixed latency: 100,14 ms
	module: 24
	properties:
		device.master_device = "alsa_input.pci-0000_04_00.6.analog-stereo"
		device.class = "filter"
		device.intended_roles = "phone"
		device.description = "Family 17h (Models 10h-1fh) HD Audio Controller Estèreo analògic (echo cancelled with Family 17h (Models 10h-1fh) HD Audio Controller Estèreo analògic)"
		device.icon_name = "audio-input-microphone"
    index: 4
	name: <noechosink.monitor>
	driver: <module-echo-cancel.c>
	flags: DECIBEL_VOLUME LATENCY 
	state: IDLE
	suspend cause: (none)
	priority: 1000
	volume: mono: 65536 / 100% / 0,00 dB
	        balance 0,00
	base volume: 65536 / 100% / 0,00 dB
	volume steps: 65537
	muted: no
	current latency: 0,00 ms
	max rewind: 11 KiB
	sample spec: float32le 1ch 32000Hz
	channel map: mono
	             Mono
	used by: 0
	linked by: 0
	fixed latency: 100,14 ms
	monitor_of: 2
	module: 24
	properties:
		device.description = "Monitor of Family 17h (Models 10h-1fh) HD Audio Controller Estèreo analògic (echo cancelled with Family 17h (Models 10h-1fh) HD Audio Controller Estèreo analògic)"
		device.class = "monitor"
		device.icon_name = "audio-input-microphone"
    index: 5
	name: <alsa_output.pci-0000_04_00.1.hdmi-stereo.monitor>
	driver: <module-alsa-card.c>
	flags: DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
	state: SUSPENDED
	suspend cause: IDLE
	priority: 1030
	volume: front-left: 65536 / 100% / 0,00 dB,   front-right: 65536 / 100% / 0,00 dB
	        balance 0,00
	base volume: 65536 / 100% / 0,00 dB
	volume steps: 65537
	muted: no
	current latency: 0,00 ms
	max rewind: 0 KiB
	sample spec: s16le 2ch 44100Hz
	channel map: front-left,front-right
	             Estèreo
	used by: 0
	linked by: 0
	configured latency: 0,00 ms; range is 0,50 .. 1999,82 ms
	monitor_of: 3
	card: 0 <alsa_card.pci-0000_04_00.1>
	module: 7
	properties:
		device.description = "Monitor of HD-Audio Generic Digital Stereo (HDMI)"
		device.class = "monitor"
		alsa.card = "0"
		alsa.card_name = "HD-Audio Generic"
		alsa.long_card_name = "HD-Audio Generic at 0xfe6c8000 irq 86"
		alsa.driver_name = "snd_hda_intel"
		device.bus_path = "pci-0000:04:00.1"
		sysfs.path = "/devices/pci0000:00/0000:00:08.1/0000:04:00.1/sound/card0"
		device.bus = "pci"
		device.vendor.id = "1002"
		device.vendor.name = "Advanced Micro Devices, Inc. [AMD/ATI]"
		device.product.id = "1637"
		device.string = "0"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-pci"
    index: 12
	name: <nui_mic_denoised_out.monitor>
	driver: <module-null-sink.c>
	flags: DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
	state: RUNNING
	suspend cause: (none)
	priority: 1000
	volume: front-left: 65536 / 100% / 0,00 dB,   front-right: 65536 / 100% / 0,00 dB
	        balance 0,00
	base volume: 65536 / 100% / 0,00 dB
	volume steps: 65537
	muted: no
	current latency: 0,00 ms
	max rewind: 1 KiB
	sample spec: s16le 2ch 48000Hz
	channel map: front-left,front-right
	             Estèreo
	used by: 1
	linked by: 1
	configured latency: 10,00 ms; range is 0,50 .. 2000,00 ms
	monitor_of: 8
	module: 36
	properties:
		device.description = "Monitor of Sortida nul·la"
		device.class = "monitor"
		device.icon_name = "audio-input-microphone"
    index: 13
	name: <nui_mic_raw_in.monitor>
	driver: <module-ladspa-sink.c>
	flags: DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
	state: IDLE
	suspend cause: (none)
	priority: 1000
	volume: front-left: 65536 / 100% / 0,00 dB,   front-right: 65536 / 100% / 0,00 dB
	        balance 0,00
	base volume: 65536 / 100% / 0,00 dB
	volume steps: 65537
	muted: no
	current latency: 0,00 ms
	max rewind: 2 KiB
	sample spec: float32le 2ch 48000Hz
	channel map: front-left,front-right
	             Estèreo
	used by: 0
	linked by: 0
	configured latency: 2000,00 ms; range is 0,50 .. 2000,00 ms
	monitor_of: 9
	module: 37
	properties:
		device.description = "Monitor of LADSPA Plugin Noise Suppressor for Voice (Mono) on Sortida nul·la"
		device.class = "monitor"
		device.icon_name = "audio-input-microphone"
    index: 14
	name: <nui_mic_remap>
	driver: <module-remap-source.c>
	flags: DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
	state: RUNNING
	suspend cause: (none)
	priority: 1000
	volume: front-left: 60395 /  92% / -2,13 dB,   front-right: 60395 /  92% / -2,13 dB
	        balance 0,00
	base volume: 65536 / 100% / 0,00 dB
	volume steps: 65537
	muted: no
	current latency: 0,00 ms
	max rewind: 1 KiB
	sample spec: s16le 2ch 48000Hz
	channel map: front-left,front-right
	             Estèreo
	used by: 2
	linked by: 2
	configured latency: 10,00 ms; range is 0,50 .. 2000,00 ms
	module: 39
	properties:
		device.master_device = "nui_mic_denoised_out.monitor"
		device.class = "filter"
		device.description = "NoiseTorch Microphone"
		device.icon_name = "audio-input-microphone"
`

**Comment by lawl** [comment] 2020-12-23 16:58
Sorry, one more question, you're currently loading it with the echo cancel module inbetween, does it also work fine if you load it with your input directly, without the echo cancel module chained in front of it?

**Comment by Pijuli** [comment] 2020-12-23 17:08
No problem, at all.

If I load it directly WITHOUT echo cancel... it's, my mates words: horrible and unintelligible

**Comment by lawl** [comment] 2020-12-23 17:19
> btw, why is this happening?

that's what i'd like to know to :) I don't have any affected hardware to it's really difficult finding out what's exactly going on here. But that it doesn't work without echo cancel is *very* valuable info, thanks. Would it be okay if I ping you again in the future to maybe run a few experimental builds and report their behaviour/logs?

**Comment by Pijuli** [comment] 2020-12-23 17:22
That would be the best christmas gift :laughing: 
Yes, whenever. :ok_hand:

**Comment by JJ-8** [comment] 2020-12-30 13:41
2-3 weeks ago I tried Noisetorch on a new device, because the microphone was oversensitive to noises. I have the same incompatible warning for the "Family 17h (Model 10h-1fh) HD Audio Controller" device. I tried it anyway and it resulted in having the same issue as #48. After that, I ended up using the Real-time Noise Suppression Plugin directly, which worked but was not the best solution.
I just went back and checked this issue and I saw that it could be working with echo cancel enabled. I just tried it and it seems to work!

I followed the instructions from #24 to [add an echo cancelled device](https://github.com/lawl/NoiseTorch/issues/24#issuecomment-701386011). After that, I selected the echo cancelled device in Noisetorch and enabled it.

So I can also confirm that an echo cancelled input device is working and that I don't have problems with issue #48 anymore! (I am using version 0.9.0)

**Comment by lawl** [comment] 2020-12-31 04:56
Thanks for the report @JJ-8. I also just wanted to post a quick status update.

This is taking a bit longer than expected on my side, since I would like to figure out the root of the issue here and I believe I have an idea on what the issue here is that happens to coincide with some work that we'll require for PipeWire support anyways.

An obvious work-around that would be fairly simple would of course be to just force load the echo cancel module for affected devices as a work around, but for the moment I would still prefer to figure this out and fix properly.

**Comment by lawl** [comment] 2021-01-04 18:09
@Pijuli I have prepared a build here: 
[noisetorch.zip](https://github.com/lawl/NoiseTorch/files/5766135/noisetorch.zip)

This doesn't contain any special logging so far, but a complete rewrite of some parts. I'm wondering how that behaves on your system with and without the echo cancel module chainloaded. Does the denoising behave any different to the currently released version?

**Comment by JJ-8** [comment] 2021-01-06 16:07
I know you haven't asked by to test it, but I was curious and I tested it anyway :)
I haven't tested audio quality. I was mostly focusing on issue #48. I tried reloading NoiseTorch about 25 times every time, because I could not trigger the 2 seconds of latency consistently. The results:
- Version 0.9.0, non-echo cancelled microphone: 2 seconds bug
- Version 0.9.0, echo cancelled microphone: no 2 seconds bug
- 0.9.0-2-gf3c11be, non-echo cancelled microphone: 2 seconds bug
- 0.9.0-2-gf3c11be, echo cancelled microphone: no 2 seconds bug

With and without the echo cancel module chain-loaded does not seem to affect the results.
So unfortunately, #48 still exists in the test build...
If you want me to test something again for issue #48, I am happy to help!

**Comment by lawl** [comment] 2021-01-06 16:32
Thanks @JJ-8. The reason I'm so interested in @Pijuli's system specifically, is because he doesn't seem to be affected by the 2 seconds of latency issue. This is why there are two open issues for these devices, some people say there's latency and crackling, and for others there seems to be just extreme distortion or flat out silence. Though `pacmd` still logs

    	configured latency: 2000,00 ms; range is 0,50 .. 2000,00 ms

There is one thing you could test. 
[noisetorch.zip](https://github.com/lawl/NoiseTorch/files/5776923/noisetorch.zip)

Before using this one always make sure to restart pulse, or the new plugin won't load correctly. `pulseaudio -k` And then load it in mircophone only mode (disable headphone filtering).

Now check your pulse log and you should see some spam like this:

```
NoiseTorch: Received 48 samples
NoiseTorch: Received 96 samples
NoiseTorch: Received 96 samples
```
in your pulseaudio log (`journalctl -fb /usr/bin/pulseaudio`). If you could grab a chunk of these (20 lines or so that seem representative should be enough) with and without echo-cancel chainloaded, that would be interesting.

**Comment by JJ-8** [comment] 2021-01-06 18:17
Here are the files:
- [test-build-with-echo-cancelling-loaded-and-echo-cancelled-microphone.txt](https://github.com/lawl/NoiseTorch/files/5777454/test-build-with-echo-cancelling-loaded-and-echo-cancelled-microphone.txt)
- [test-build-with-echo-cancelling-loaded-and-non-echo-cancelled-microphone-no-latency.txt](https://github.com/lawl/NoiseTorch/files/5777455/test-build-with-echo-cancelling-loaded-and-non-echo-cancelled-microphone-no-latency.txt)
- [test-build-with-echo-cancelling-loaded-and-non-echo-cancelled-microphone-with-2-seconds-latency.txt](https://github.com/lawl/NoiseTorch/files/5777456/test-build-with-echo-cancelling-loaded-and-non-echo-cancelled-microphone-with-2-seconds-latency.txt)
- [test-build-without-echo-cancelling-loaded-no-2-seconds-latency.txt](https://github.com/lawl/NoiseTorch/files/5777457/test-build-without-echo-cancelling-loaded-no-2-seconds-latency.txt)
- [test-build-without-echo-cancelling-loaded-with-2-seconds-latency.txt](https://github.com/lawl/NoiseTorch/files/5777458/test-build-without-echo-cancelling-loaded-with-2-seconds-latency.txt)

Thank you so much for looking into this problem!

**Comment by lawl** [comment] 2021-01-06 18:39
Awesome! What I see here is that `test-build-with-echo-cancelling-loaded-and-echo-cancelled-microphone.txt` which is the only one with the echo cancel module chainloaded seems to have a noticably different pattern. And receive samples much more uniformly.

The good news is that confirms my suspicion on what I thought is happening here, but the bad news is that i'm not quite sure yet why this new build doesn't fix it. I'm also kind of confused by all those `1 samples`, doesn't make any sense to send over one single float to denoise.

I'm also not quite sure yet where to go from here, but i'll think about it and dig through pulseaudio code a bit and probably come back with another test build. But at least this is (probably) progress!

**Comment by lawl** [comment] 2021-01-08 04:36
I've spent some time digging through source and static analysis only gets me so far. It would be interesting if someone could apply the following patch to pulse:

```diff

diff --git a/src/modules/module-loopback.c b/src/modules/module-loopback.c
index 871f01166..31d90ef58 100644
--- a/src/modules/module-loopback.c
+++ b/src/modules/module-loopback.c
@@ -329,8 +329,9 @@ static void adjust_rates(struct userdata *u) {
      * or source/sink latency */
     run_hours = u->iteration_counter * u->real_adjust_time / PA_USEC_PER_SEC / 3600;
     u->iteration_counter +=1;
-
+    printf("Underrun counter: %d\n",u->underrun_counter);
     /* If we are seeing underruns then the latency is too small */
+
     if (u->underrun_counter > 2) {
         pa_usec_t target_latency;
 
@@ -1016,6 +1017,9 @@ static void set_sink_input_latency(struct userdata *u, pa_sink *sink) {
     if (u->min_source_latency > requested_latency) {
         latency = PA_MAX(u->latency, u->minimum_latency);
         requested_latency = (latency - u->min_source_latency) / 2;
+        if (u->fixed_alsa_source)
+            requested_latency = PA_MIN(requested_latency, (latency - u->core->default_fragment_size_msec * PA_USEC_PER_MSEC) / 2);
+
     }
 
     latency = PA_CLAMP(requested_latency , u->min_sink_latency, u->max_sink_latency);
```

What would also be interesting, when you get the static/distortion from pulse and then just leave it recording for a few minutes, does the underrun counter we print to the pulseaudio log with this patch go down and is the distorion/crackling gone once that counter reliably prints 0 (if it ever does)?

**Comment by Pijuli** [comment] 2021-01-08 09:09
> @Pijuli I have prepared a build here:
> [noisetorch.zip](https://github.com/lawl/NoiseTorch/files/5766135/noisetorch.zip)
> 
> This doesn't contain any special logging so far, but a complete rewrite of some parts. I'm wondering how that behaves on your system with and without the echo cancel module chainloaded. Does the denoising behave any different to the currently released version?

Hi! Im back from Christmas holidays.
So... WITH echo cancel everything seems to be working as it worked for me before. No problem here.
WITHOUT echo cancel, I have a delay in the audio.
Does it makes sense?

I could try patching pulse... but I don't have the knowledge. If you can help me I'd be glad to help

**Comment by lawl** [comment] 2021-01-08 11:00
Thanks @Pijuli 

Before you reported

> If I load it directly WITHOUT echo cancel... it's, my mates words: horrible and unintelligible

Now it's not distorted anymore?

**Comment by JJ-8** [comment] 2021-01-11 16:52
After _a lot_ of struggling, I managed to install pulseaudio from source. I have `pulseaudio 14.0-92-gb1bdd` installed now (latest git version with the patch in it).
It seems that the 2 seconds latency is gone with this version. I tried to reload pulseaudio multiple times and I can not get the latency back. I am not using the echo-cancel module (and I also don't want to try, because the modules where very annoying while installing from source).
However, I get some feedback from pulseaudio:
```
W: [pulseaudio] pid.c: Stale PID file, overwriting.
W: [pulseaudio] module-loopback.c: Configured latency of 1.00 ms is smaller than minimum latency, using minimum instead
W: [pulseaudio] module-loopback.c: Cannot set requested source latency of 14.62 ms, adjusting to 100.14 ms
W: [pulseaudio] module-remap-source.c: No remapping configured, proceeding nonetheless!
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 36.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 41.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 46.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 51.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 56.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 61.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 66.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 71.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 76.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 81.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 86.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 91.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 96.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 101.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 106.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 111.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 116.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 121.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 126.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 131.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 136.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 141.75 ms
```
It seems to stabilize on 141.75 ms. I don't know if you already know this output.
@lawl Does this help you? I can test some more if you want, because now I have it finally installed :)

**Comment by lawl** [comment] 2021-01-12 04:52
@JJ-8 yes this already helps, this is about what it should look like. My theory currently is that it takes quite a while for it to stabilize, is that correct? (more than a couple of seconds). *If* that's the case, can you confirm that you experience distortion (you can e.g. record yourself with Audacity or something to test) in your denoised microphone before that has stabilized but not anymore after?

**Comment by JJ-8** [comment] 2021-01-12 16:19
Yes it takes a while (about 5-10 seconds per 5 ms increase) for it to stabilize. I forgot to mention that.
I tested some more this day and I noticed that it is not not increasing up to 141.75 ms anymore. It seems to be different between each reload of NoiseTorch
```
W: [pulseaudio] pid.c: Stale PID file, overwriting.
W: [pulseaudio] module-loopback.c: Configured latency of 1.00 ms is smaller than minimum latency, using minimum instead
W: [pulseaudio] module-loopback.c: Cannot set requested source latency of 14.62 ms, adjusting to 100.14 ms
W: [pulseaudio] module-remap-source.c: No remapping configured, proceeding nonetheless!
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 36.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 41.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 46.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 51.75 ms
```
and for example
```
W: [pulseaudio] pid.c: Stale PID file, overwriting.
W: [pulseaudio] module-loopback.c: Configured latency of 1.00 ms is smaller than minimum latency, using minimum instead
W: [pulseaudio] module-loopback.c: Cannot set requested source latency of 14.62 ms, adjusting to 100.14 ms
W: [pulseaudio] module-remap-source.c: No remapping configured, proceeding nonetheless!
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 36.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 41.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 46.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 51.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 56.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 61.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 66.75 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 71.75 ms
```
Before discussing the results, I have to mention that I already have my original microphone on 20%-30% volume. This is because my microphone is _very_ sensitive and if I let NoiseTorch filter the microphone while it is at 100%, the results will be horrible because of all the noise. However, NoiseTorch itself is at 100%.

This is what I did:
1. Kill original pulseaudio and have the latest version ready to activate
2. Active the new-version pulseaudio
3. Quickly load NoiseTorch (I am not using the echo-cancel module)
4. Start recording with Audacity

@lawl It is exactly what you predicted. It is distorted until it stabilizes. I have no idea about the inner working of pulseaudio, but for me it looks like pulseaudio is increasing latency because of the distortion. Sometimes, the distortion just doesn't go away and it keeps increasing the latency (I had once a latency of 231.75 ms before I killed it while it was still distorted).
Hopefully this helps! Let me know if you want me to testing something again!

Also, when I was listening to my own recording, I noticed that the "st"-sound is filtered. Because my language contains actually quite a lot of "st"-words, the recording sounds like there were a lot of cuts in the middle of some words. Is there a way to solve this? Or is it the fault of the Real-time Noise Suppression Plugin and an English-only data set?

Thank you so much for investigating this issue!

**Comment by lawl** [comment] 2021-01-25 15:56
Sorry for the long wait, I was busy.

I've made a new test build here: 
[noisetorch.zip](https://github.com/lawl/NoiseTorch/files/5867715/noisetorch.zip)

For me this one adjusts the latency correctly in ~2 seconds, which I think is probably acceptable:

```
Underrun counter: 15
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 55.00 ms
Underrun counter: 43
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 60.00 ms
Underrun counter: 0
```

I'm hoping this also works on real affected hardware. The patched pulseaudio is still required for this.


>  Because my language contains actually quite a lot of "st"-words, the recording sounds like there were a lot of cuts in the middle of some words. Is there a way to solve this?

Can you try turning down the "Voice Activation Threshold" slider and see if that changes anything?

**Comment by lapineige** [comment] 2021-01-31 14:18
> There is one thing you could test without building pulseaudio from source.
noisetorch.zip
>
>Before using this one always make sure to restart pulse, or the new plugin won't load correctly. pulseaudio -k And then load it in mircophone only mode (disable headphone filtering).
>
>Now check your pulse log and you should see some spam like this:

I did test this build, after killing pulseaudio, in microphone only filtering mode.
I don't have this lines in the logs, and still experience the 2s latency.

But there is some new log:

> Failed to create sink input: sink is suspended.
>  module-combine is deprecated: Please use module-combine-sink instead of module-combine!
> We will now load module-combine-sink. Please make sure to remove module-combine from your configuration.
> Cannot set requested sink latency of 9223372036854752,00 ms, adjusting to 2000,00 ms
> Cannot set requested source latency of 16,67 ms, adjusting to 100,14 ms
> No remapping configured, proceeding nonetheless!

**Comment by lawl** [comment] 2021-01-31 22:33
Thank you for trying to help @lapineige but unfortunately you are not helping. This needs to be tested under the exact described setups with applied patches or it is absolutely meaningless.

**Comment by lapineige** [comment] 2021-02-01 07:39
Ok, I did not understand that, I thought this was a workaround without the patch.

**Comment by JJ-8** [comment] 2021-02-01 18:17
Hi @lawl, sorry for my slow response. I did not have much time to test this last week.
I just tested this and it seems to work exactly as you described! I am still running the same version of pulseaudio as my earlier tests (I did not update the git download). I don't have the 2 seconds bug anymore! This is the output I get:
```
W: [pulseaudio] pid.c: Stale PID file, overwriting.
W: [pulseaudio] module-loopback.c: Cannot set requested source latency of 16.67 ms, adjusting to 100.14 ms
W: [pulseaudio] module-remap-source.c: No remapping configured, proceeding nonetheless!
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 55.00 ms
W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 60.00 ms
E: [alsa-sink-ALC269VC Analog] alsa-sink.c: ALSA woke us up to write new data to the device, but there was actually nothing to write.
E: [alsa-sink-ALC269VC Analog] alsa-sink.c: Most likely this is a bug in the ALSA driver 'snd_hda_intel'. Please report this issue to the ALSA developers.
E: [alsa-sink-ALC269VC Analog] alsa-sink.c: We were woken up with POLLOUT set -- however a subsequent snd_pcm_avail() returned 0 or another value < min_avail.
E: [pulseaudio] sink.c: Assertion 'PA_SINK_IS_LINKED(s->state)' failed at pulsecore/sink.c:924, function pa_sink_suspend(). Aborting.
fish: “/usr/local/bin/pulseaudio” terminated by signal SIGABRT (Abort)
```
I got the assertion error as soon as I unload Noisetorch (and also the ALSA error I think). Maybe this is because I have disabled automatic restart of pulseaudio for testing purposes. I don't know why I got the ALSA error, but maybe that is not relevant. This is also the only time I got this error (I tested it multiple times and only got the assertion error each time just before the unload).

I have set the Voice Activation Threshold to 0% and now the "st"-words seems to be not filtered anymore.

I think you fixed the bug! 
Thank you so much for putting your time and effort into this! It is really appreciated :)

**Comment by lawl** [comment] 2021-02-02 06:25
Regarding the Assertion, well pulseaudio shouldn't crash irregradless of what we're doing, I'll assume that's an unrelated bug in PA for now, though you may want to report it upstream.

Can I just for clarity ask, is this with the regular upstream git, or is this with the patch applied? (Since upstream git now a patch merged that's slightly different, just so i know which one)

> I have set the Voice Activation Threshold to 0% and now the "st"-words seems to be not filtered anymore.

It's unfortunate that you need to turn it all the way down to 0. If you have a video on youtube or a recording to demonstrate this issue i can see if we can finetune some values a bit, but no guarantees.

Additionally I've pushed the change on our side [here](febccb207b518aa73d142acae2befa9d20e427d8) so it will be part of the next NoiseTorch release, but I won't do an extra release for it, since it still requires people to have a fixed PulseAudio.

**Comment by JJ-8** [comment] 2021-02-02 11:50
Good that you asked about the pulseaudio version @lawl. The version I tested yesterday was `pulseaudio 14.0-92-gb1bdd`. It was the latest version at the time of [testing this 22 days ago](https://github.com/lawl/NoiseTorch/issues/77#issuecomment-758082741). I just did a fresh pull of the pulseaudio repository and reinstalled it. I now tried it with `pulseaudio 14.0-184-gc05c6` and it seems to still work. I also don't get the assertion errors I got yesterday, so that is also solved!
So I did not apply any patches you provided but instead downloaded the latest pulseaudio from git.

I think I can deal with the 0% threshold. I have a global push-to-talk extension, so I can easily mute the microphone when I start typing for example. The noise of the microphone itself is still filtered.
