### ISSUE TITLE
Noisetorch crashes on Fedora 35

### ISSUE THREAD

**Issue by ElTimablo** [lawl/NoiseTorch#186] opened 2021-10-19 23:29 UTC
Attempting to assign the Noisetorch microphone as an input device in Discord causes Noisetorch to "unload," by which I mean the "reload" and "unload" buttons disappear and the interface resets to the state it's in on boot. All sound input stops working as well. Worked fine on Fedora 34.

**Comment by lawl** [comment] 2021-10-19 23:31
can you post your `pipewire-pulse` log?

**Comment by ElTimablo** [comment] 2021-10-19 23:34
Where would I find that? I've got core dumps, but I'm not sure how to read them.

**Comment by lawl** [comment] 2021-10-19 23:38
If you have core dumps, that already answers my question. Please file a bug with fedora. A pipewire-pulse crash is not a noisetorch bug. Duplicate of #181

Feel free to drop a link to the fedora issue here though, so others can see it.

**Closed by lawl** 2021-10-19 23:38 UTC

**Comment by ElTimablo** [comment] 2021-10-20 01:24
And you sound like the type of dev that closes as many bugs as "not my problem" as possible. EasyEffects works fine. Have a nice day.
