### ISSUE TITLE
Pipewire Issue; "PulseAudio error: commandLoadModule -> No such entity

### ISSUE THREAD

**Issue by surfrock66** [lawl/NoiseTorch#235] opened 2022-03-22 19:06 UTC
I know PipeWire support is alpha, so this is an FYI and in no way a complaint.  The app launches, but immediately goes to "NoiseTorch inactive" ~5 seconds after starting.  This is an up-to-date ubuntu system.  Log output:

```
surfrock66@sr66-thelio:~$ noisetorch -log
2022/03/22 12:03:33 Application starting. Version: 0.11.4 (official)
2022/03/22 12:03:33 CAP_SYS_RESOURCE: true
2022/03/22 12:03:33 Checking if config needs to be initialized
2022/03/22 12:03:33 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/surfrock66/.config'
2022/03/22 12:03:33 Wrote temp librnnoise to: /tmp/librnnoise-2423930512.so
2022/03/22 12:03:33 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/surfrock66/.config'
2022/03/22 12:03:33 Audioserver package name: PulseAudio (on PipeWire 0.3.47)
2022/03/22 12:03:33 Audioserver package version: 15.0.0
2022/03/22 12:03:33 Detected PipeWire
2022/03/22 12:03:33 Checking for updates
2022/03/22 12:03:33 Getting caps for: /home/surfrock66/.local/bin/noisetorch
2022/03/22 12:03:33 Audioserver package name: PulseAudio (on PipeWire 0.3.47)
2022/03/22 12:03:33 Audioserver package version: 15.0.0
2022/03/22 12:03:33 Detected PipeWire
2022/03/22 12:03:33 Connected to audio server. Server name 'PipeWire'
2022/03/22 12:03:33 Output alsa_output.pci-0000_0b_00.4.analog-stereo, {Index:50 Name:alsa_output.pci-0000_0b_00.4.analog-stereo Description:Starship/Matisse HD Audio Controller Analog Stereo SampleSpec:{Format:7 Channels:2 Rate:48000} ChannelMap:[1 2] ModuleIndex:4294967295 Cvolume:[19672 19672] Muted:false MonitorSourceIndex:50 MonitorSourceName:alsa_output.pci-0000_0b_00.4.analog-stereo.monitor Latency:0 Driver:PipeWire Flags:183 PropList:map[alsa.card:2 alsa.card_name:HD-Audio Generic alsa.class:generic alsa.device:0 alsa.driver_name:snd_hda_intel alsa.id:ALC1220 Analog alsa.long_card_name:HD-Audio Generic at 0xfca00000 irq 142 alsa.name:ALC1220 Analog alsa.resolution_bits:16 alsa.subclass:generic-mix alsa.subdevice:0 alsa.subdevice_name:subdevice #0 api.alsa.path:front:2 api.alsa.pcm.card:2 api.alsa.pcm.stream:playback audio.adapt.follower: audio.channels:2 audio.position:FL,FR card.profile.device:4 client.id:32 clock.quantum-limit:8192 device.api:alsa device.bus:pci device.bus_path:pci-0000:0b:00.4 device.class:sound device.description:Starship/Matisse HD Audio Controller Analog Stereo device.icon_name:audio-card-analog device.id:46 device.profile.description:Analog Stereo device.profile.name:analog-stereo device.routes:2 factory.id:18 factory.mode:merge factory.name:api.alsa.pcm.sink library.name:audioconvert/libspa-audioconvert media.class:Audio/Sink node.driver:true node.max-latency:16384/48000 node.name:alsa_output.pci-0000_0b_00.4.analog-stereo node.nick:HD-Audio Generic node.pause-on-idle:false object.id:33 object.path:alsa:pcm:2:front:2:playback object.serial:50 priority.driver:881 priority.session:881] RequestedLatency:0 BaseVolume:65536 SinkState:0 NVolumeSteps:0 CardIndex:45 Ports:[{Name:analog-output-lineout Description:Line Out Pririty:9000 Available:2} {Name:analog-output-headphones Description:Headphones Pririty:9900 Available:1}] ActivePortName:analog-output-lineout Formats:[{Encoding:1 PropList:map[]}]}
2022/03/22 12:03:33 Output alsa_output.pci-0000_09_00.1.hdmi-stereo, {Index:49931 Name:alsa_output.pci-0000_09_00.1.hdmi-stereo Description:TU104 HD Audio Controller Digital Stereo (HDMI) SampleSpec:{Format:3 Channels:2 Rate:48000} ChannelMap:[1 2] ModuleIndex:4294967295 Cvolume:[48287 48287] Muted:false MonitorSourceIndex:49931 MonitorSourceName:alsa_output.pci-0000_09_00.1.hdmi-stereo.monitor Latency:0 Driver:PipeWire Flags:422 PropList:map[alsa.card:0 alsa.card_name:HDA NVidia alsa.class:generic alsa.device:3 alsa.driver_name:snd_hda_intel alsa.id:HDMI 0 alsa.long_card_name:HDA NVidia at 0xfc080000 irq 140 alsa.name:HDMI 0 alsa.resolution_bits:16 alsa.subclass:generic-mix alsa.subdevice:0 alsa.subdevice_name:subdevice #0 api.alsa.path:hdmi:0 api.alsa.pcm.card:0 api.alsa.pcm.stream:playback audio.adapt.follower: audio.channels:2 audio.position:FL,FR card.profile.device:7 client.id:32 clock.quantum-limit:8192 device.api:alsa device.bus:pci device.bus_path:pci-0000:09:00.1 device.class:sound device.description:TU104 HD Audio Controller Digital Stereo (HDMI) device.icon_name:audio-card-hdmi device.id:44 device.profile.description:Digital Stereo (HDMI) device.profile.name:hdmi-stereo device.routes:1 factory.id:18 factory.mode:merge factory.name:api.alsa.pcm.sink library.name:audioconvert/libspa-audioconvert media.class:Audio/Sink node.driver:true node.name:alsa_output.pci-0000_09_00.1.hdmi-stereo node.nick:HDA NVidia node.pause-on-idle:false object.id:131 object.path:alsa:pcm:0:hdmi:0:playback object.serial:49931 priority.driver:696 priority.session:696] RequestedLatency:0 BaseVolume:65536 SinkState:2 NVolumeSteps:0 CardIndex:43 Ports:[{Name:hdmi-output-0 Description:HDMI / DisplayPort Pririty:5900 Available:2}] ActivePortName:hdmi-output-0 Formats:[{Encoding:1 PropList:map[]}]}
2022/03/22 12:03:36 Loading supressor for pipewire
2022/03/22 12:03:36 Error loading input: PulseAudio error: commandLoadModule -> No such entity
2022/03/22 12:03:36 PulseAudio error: commandLoadModule -> No such entity
2022/03/22 12:03:46 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/surfrock66/.config'
```

**Comment by lawl** [comment] 2022-03-22 19:09
Duplicate of this: https://github.com/lawl/NoiseTorch/issues/232 ?

**Comment by surfrock66** [comment] 2022-03-22 20:49
Might be, I'll reboot when I can to test.  I didn't see that when I looked.

**Comment by lawl** [comment] 2022-03-22 20:51
Exactly the same Pipewire version with the same error. Might also be that they rebooted and got a new pipewire version, unsure, might also be worth to try something other than exactly PipeWire 0.3.47

**Comment by lawl** [comment] 2022-03-27 02:06
closing this for now, let me know when you have an update.

**Closed by lawl** 2022-03-27 02:06 UTC

**Comment by surfrock66** [comment] 2022-03-27 02:19
Yes, totally forgot to update as I rebooted then immediately left for a trip, it seemed to work.  I didn't test the actual audio, but it enabled successfully.
