### ISSUE TITLE
[feature request] start with the system

### ISSUE THREAD

**Issue by Kazvko** [lawl/NoiseTorch#149] opened 2021-06-11 19:49 UTC
I've been using NoiseTorch for my appointments as a psychologist, and would love to get it to work automatically on boot, since 80% of my work is based on online meetings. I imagine it's something simple to implement via the interface, but I wouldn't mind adding manual as startup apps, except I don't know exactly how to do it.

Thanks in advance

**Comment by lawl** [comment] 2021-06-11 19:56
Duplicate of #6.

For an unsupported method in the meantime: https://github.com/lawl/NoiseTorch/wiki/Start-automatically-with-Systemd

**Closed by lawl** 2021-06-11 19:56 UTC
