### ISSUE TITLE
Option to activate on start-up?

### ISSUE THREAD

**Issue by fosspill** [lawl/NoiseTorch#13] opened 2020-07-17 06:34 UTC
Hi, it seems NoiseTorch starts disabled, regardless of the previous state.

Having the possibility to having it activate on startup, including using the previous settings would be fantastic.

**Comment by lawl** [comment] 2020-07-17 06:37
Hey!

I think this is a duplicate of #6 . Could you add a thumbs up there so I can gauge the demand for this? If you don't think this is a duplicate feel free to reopen.

**Closed by lawl** 2020-07-17 06:37 UTC

**Comment by fosspill** [comment] 2020-07-17 06:38
Oh sorry, I must be blind. Added a thumbsup.
