### ISSUE TITLE
No input on NoiseTorch Microphone

### ISSUE THREAD

**Issue by westleyfsm** [lawl/NoiseTorch#12] opened 2020-07-17 03:30 UTC
I do not get any input from the NoiseTorch device. 

Sink list:

```
$ pactl list sources short
0	alsa_output.pci-0000_00_1f.3.analog-stereo.monitor	module-alsa-card.c	s16le 2ch 44100Hz	RUNNING
1	alsa_input.pci-0000_00_1f.3.analog-stereo	module-alsa-card.c	s16le 2ch 44100Hz	RUNNING
2	alsa_output.pci-0000_65_00.1.hdmi-stereo-extra2.monitor	module-alsa-card.c	s16le 2ch 44100Hz	SUSPENDED
3	nui_mic_denoised_out.monitor	module-null-sink.c	s16le 2ch 44100Hz	RUNNING
4	nui_mic_raw_in.monitor	module-ladspa-sink.c	float32le 2ch 44100Hz	IDLE
5	nui_mic_remap	module-remap-source.c	s16le 2ch 44100Hz	IDLE
```

NoiseTorch output:

```
$ noisetorch 
2020/07/16 21:26:55 Application starting. Version: 0.3.4-beta
2020/07/16 21:26:55 Checking if config needs to be initialized
2020/07/16 21:26:55 Wrote temp librnnoise to: /tmp/librnnoise-630975120.so
2020/07/16 21:26:55 Checking for updates
2020/07/16 21:26:59 Loading supressor
2020/07/16 21:26:59 Loaded null sink as idx: 26
2020/07/16 21:27:00 Loaded ladspa sink as idx: 27
2020/07/16 21:27:01 Loaded loopback as idx: 28
2020/07/16 21:27:01 Loaded ladspa sink as idx: 29
```

I am on up-to-date Manjaro.

**Comment by lawl** [comment] 2020-07-17 04:32
4 nui_mic_raw_in.monitor module-ladspa-sink.c float32le 2ch 44100Hz IDLE
    5 nui_mic_remap module-remap-source.c s16le 2ch 44100Hz IDLE

These two shouldn't be idle, not sure why they are. Can you check that nothing is muted in `pavucontrol` and give me the full output of `pacmd list-modules`

**Comment by westleyfsm** [comment] 2020-07-17 06:56
Nothing is muted, everything full volume in pavucontrol.

Modules:
[modules.txt](https://github.com/lawl/NoiseTorch/files/4936182/modules.txt)

**Comment by lawl** [comment] 2020-07-17 07:20
So it looks like NoiseTorch should be loaded correctly. We're gonna have to try a few different shots in the dark here.

Close NoiseTorch, then from a terminal, restart PulseAudio

    pulseaudio -k

Now unload the suspend-on-idle module with

    pacmd unload-module module-suspend-on-idle

Make sure it's unloaded by checking that

    pacmd list-modules | grep suspend-on-idle

prints nothing. Then start NoiseTorch and see if it works. (Restarting PulseAudio with `pulseaudio -k` will load the module again)

Additionally in `pavucontrol` under `Configuration` what profile does your microphone have and can you try setting it to various "Analog Stereo/(Mono?)" things and see if that changes anything?

**Comment by westleyfsm** [comment] 2020-07-17 07:29
No luck on unloading suspend.

Under configuration, I have built-in audio, which is defaulted to Analog Stereo Duplex. A long list of options mostly about output, but no option for mono anywhere.

**Comment by lawl** [comment] 2020-07-17 07:36
Okay, again in `pavucontrol` under output devices, you should see "Null Output" and "LADSPA Plugin Noise Supressor for Voice (Mono) on Null Output".

There a bar on each of those displaying audio activity, does any of them show any signs of live when you talk? Also check the bars in "Input devices" and report if you see any activity, please.

**Comment by westleyfsm** [comment] 2020-07-17 07:39
Under both output and input tabs, the only bar that shows activity is Built-in Audio Analog Stereo

**Comment by lawl** [comment] 2020-07-17 07:40
Someone just reported what seems to be the same issue [here on reddit](https://old.reddit.com/r/linux_gaming/comments/hs6uud/noisetorch_another_realtime_microphone_noise/fyc79ty/). Couriosly also on Manjaro. Have you also installed from AUR? And if so could you try removing the AUR version and try the official method, just to rule out any AUR issues?

**Comment by westleyfsm** [comment] 2020-07-17 07:43
I tried from the AUR, but uninstalled and I have been using the .tgz. I also tried Cadmus, but assumed my problem was [this.](https://github.com/josh-richardson/cadmus/issues/32)

Seems that it is something else now.

**Comment by lawl** [comment] 2020-07-17 07:51
I'm setting up a manjaro VM to try and reproduce this as it seems to disproportionately affect manjaro users.

**Comment by lawl** [comment] 2020-07-17 08:19
![image](https://user-images.githubusercontent.com/680451/87764428-e6281680-c805-11ea-9792-acebfe0e5b93.png)

Works just fine for me in a VM. So we'll have to remote debug this, but I'm out of ideas at the moment.

**Comment by westleyfsm** [comment] 2020-07-17 08:20
I see that yours is also stereo. Do you have a separate entry for a microphone profile under pavu configuration? Or is it mixed like mine?

**Comment by lawl** [comment] 2020-07-17 08:25
It's Analog Stereo Duplex, which my real non VM setup is too.

Can you give me the output of `pulseaudio --version` and `pacman -Qi pulseaudio` ?

**Comment by westleyfsm** [comment] 2020-07-17 08:28
Version is 13.0, and:

Name            : pulseaudio
Version         : 13.0-3
Description     : A featureful, general-purpose sound server
Architecture    : x86_64
URL             : https://www.freedesktop.org/wiki/Software/PulseAudio/
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : libpulse=13.0-3  rtkit  libltdl  speexdsp  tdb  orc  libsoxr
                  webrtc-audio-processing
Optional Deps   : pulseaudio-alsa: ALSA configuration (recommended) [installed]
Required By     : gnome-settings-daemon  manjaro-pulse  paprefs
                  pulseaudio-alsa  pulseaudio-bluetooth  pulseaudio-ctl
                  pulseaudio-equalizer  pulseaudio-equalizer-ladspa
                  pulseaudio-jack  pulseaudio-lirc  pulseaudio-zeroconf
Optional For    : dolphin-emu  firefox  lib32-fluidsynth  pavucontrol
                  phonon-qt5  phonon-qt5-gstreamer
Conflicts With  : None
Replaces        : pulseaudio-xen<=9.0  pulseaudio-gconf<=11.1
Installed Size  : 6.24 MiB
Packager        : Jan Alexander Steffens (heftig) <jan.steffens@gmail.com>
Build Date      : Sat 11 Jan 2020 11:25:37 AM MST
Install Date    : Wed 11 Mar 2020 06:53:40 PM MDT
Install Reason  : Installed as a dependency for another package
Install Script  : Yes
Validated By    : Signature


I just tried on a thinkpad, also Manjaro, and it fails to work the same way.

**Comment by lawl** [comment] 2020-07-17 08:37
Two more things we can try. Can you send me a few hundred lines of your pulseaudio log after loading noisetorch and attempting to use it

    journalctl -n300 --no-pager -b /usr/bin/pulseaudio

Please dump it in a [gist](https://gist.github.com/).

Additionally you could try setting up a VM yourself to see if it works there, maybe some weird hardware issue.

**Comment by westleyfsm** [comment] 2020-07-17 08:42
[Log.](https://gist.github.com/westleyfsm/0f552d8fa9bd694f54a0c251719182ec)

Some of the logs from Jul 16 are from me trying to setup the noise suppression found [here.](https://github.com/werman/noise-suppression-for-voice)

**Comment by lawl** [comment] 2020-07-17 08:48
Looks normal to me too.

**Comment by westleyfsm** [comment] 2020-07-17 08:52
I just tried it in a VM and it works there, also Manjaro. 

Assuming it is a hardware issue, my motherboard is an x299 Aorus gaming 3, audio being: ALC1220 120dB SNR HD Audio

(just for posterity)

**Comment by lawl** [comment] 2020-07-17 08:54
If it works in a VM, then I think it's either a hardware issue, or some weirdness on your (presumably) not-fresh install of manjaro. Can you also dump me the full output of

    pacmd list-sources

into a gist?

**Comment by westleyfsm** [comment] 2020-07-17 08:56
[Here.](https://gist.github.com/westleyfsm/88d3a16c0d8af2fc1c992fe53f7438d5)

**Comment by lawl** [comment] 2020-07-17 09:03
What does it say in `pavucontrol` Input Devices -> Port?

**Comment by lawl** [comment] 2020-07-17 09:08
Then I'm out of ideas again. The only way forward I currently see is if you tried this on the same hardware with a fresh manjaro image, for example a live-usb stick.

Since it works in a VM with virtual hardware, hardware and the freshness of the OS are the only 2 variables left I think, and we need to eliminate one of those.

**Comment by westleyfsm** [comment] 2020-07-17 09:12
I will try a live-usb in the morning. 
I appreciate your time.

**Comment by westleyfsm** [comment] 2020-07-17 16:00
I just tried on the live-usb, and it works. 

I can't think of anything I've done to change pulse so much that this doesn't work.

**Comment by lawl** [comment] 2020-07-17 16:03
Hmm, you could try comparing

    pacmd list-modules
    pacmd list-sources
    pacmd list-sinks

on both system and then carefully compare the output to see whats different. For now I will remove the bug label though, as it does not look like an issue with NoiseTorch.

**Comment by westleyfsm** [comment] 2020-07-17 16:38
I think I may have found a cause, but I'm not sure and I can't seem to fix it.

Sample rate on live-sub is 44100 and my install is 48000. Could this be the cause, and if so, would you know how to change it? I tried the default sample rate in daemon.conf to no avail.

**Comment by lawl** [comment] 2020-07-17 16:41
default-sample-rate = 44100

in `/etc/pulse/daemon.conf` should work, then restart pulseaudio with `pulseaudio -k`

**Comment by westleyfsm** [comment] 2020-07-17 16:44
It's still showing 48000 for list-sources.

**Comment by westleyfsm** [comment] 2020-07-17 16:52
I had to put it in ~/.pulse/daemon.conf to make it work.
It is working now.
Thanks for the patience, and hopefully this helps the other Manjaros.

**Comment by lawl** [comment] 2020-07-18 09:09
Hey @westleyfsm sorry for bugging you, I have just released [NoiseTorch](0.5.0-beta) which is a change that affects sampling rate, if you have the time, I'd be curious if that also happens to fix your issue without manually setting the configuration.

**Comment by mdillavou** [comment] 2020-07-18 16:00
I am on Fedora 32 and was having similar issues. I tried all the steps listed and none helped. Eventually, I tried turning the Voice Activation Threshold down from the default of 95% to 70% and it worked perfectly!

**Comment by lawl** [comment] 2020-07-18 16:05
Oh, yeah maybe i shouldn't default to 95%

**Comment by mdillavou** [comment] 2020-07-18 16:24
Well, after unloading and loading, it stopped working again...

**Comment by FDrico** [comment] 2020-07-18 18:52
I seem to have exactly the same problem, and none of the above suggestions solved it. I'm on Xubuntu 19.10.

**Comment by okonech** [comment] 2020-07-19 09:19
Hey, I'm on 

Operating System: Manjaro Linux 
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.15.0
Kernel Version: 5.7.0-3-MANJARO
OS Type: 64-bit
Processors: 12 × Intel® Core™ i7-8700K CPU @ 3.70GHz
Memory: 15.6 GiB of RAM

I manually installed the 0.5.0-beta, it did not work by default.
Once I applied the ~/.pulse/daemon.conf change, it started working very well!

**Comment by lawl** [comment] 2020-07-19 11:12
@mdillavou @FDrico can you two please open separate issues of none of the solutions here worked for you?

**Comment by lawl** [comment] 2020-07-19 12:07
I've created a wiki page for the solution [here](https://github.com/lawl/NoiseTorch/wiki/Troubleshooting) and am closing this again. Please create a new issues of none of this works.

**Closed by lawl** 2020-07-19 12:07 UTC
Labels: bug, question

**Comment by mdillavou** [comment] 2020-07-20 12:55
Not setting NoiseTorch as the default microphone in gnome fixed this for me.
