### ISSUE TITLE
Noisetorch still available as an input source even after being disabled.

### ISSUE THREAD

**Issue by DuttaAB-dev** [lawl/NoiseTorch#224] opened 2022-02-25 03:50 UTC
![image](https://user-images.githubusercontent.com/61903332/155650034-165dd16c-b6f1-4c6d-b732-9127f97d6ea5.png)

The heading says it all. Also, selecting any of this options after disabling noisetorch causes the whole desktop environment to crash.

I am on fedora 35 with pipewire as the audio server and wayland as the display server. Can't confirm if it is the same in Xorg.

**Comment by lawl** [comment] 2022-02-25 12:33
Cannot reproduce in my fedora 35 VM. Please provide *detailed* reproduction steps and logs.

**Comment by DuttaAB-dev** [comment] 2022-02-26 09:25
I dont know how this happens for sure, except that it just happens after using if for quiet a long time, with disabling and then enabling it a few times in between. I wish I knew a sure way to reproduce this issue, which I am still trying to find a sure way to.
But trust me, this issue has been far too common to be ignored, both in pop os and in fedora, well atleast in my experience.

And can you please guide me the way for producing logs?

**Comment by lawl** [comment] 2022-02-26 13:55
>  And can you please guide me the way for producing logs?


https://github.com/lawl/NoiseTorch/wiki/Troubleshooting

**Comment by lawl** [comment] 2022-02-26 13:55
i'm closing this for the moment, please reopen when you figure out how to reproduce it.

**Closed by lawl** 2022-02-26 13:55 UTC

**Comment by DuttaAB-dev** [comment] 2022-02-26 18:13
@lawl thanks for the guidance! And, this happened to me again, with the desktop crashing and all of the other goodies. Still in the search for a sure way to reproduce this issue, will notify when I find one.
