### ISSUE TITLE
I hear myself when i switch audio devices

### ISSUE THREAD

**Issue by Alfagun74** [lawl/NoiseTorch#103] opened 2021-03-11 11:03 UTC
So i usually switch between my headphones and speakers.

If i need to talk to someone i use the headphones, if i want to enjoy some alone time i use speakers.

However, with Noisetorch activated on my headphones, when i switch to the speakers or any other sound device, i start to hear my denoised microphone output. Even if i switch back to headphones i still hear it. I have to reload everything so it doesn't happen but it gets annoying.

Any Ideas how i can fix this?

**Comment by lawl** [comment] 2021-03-11 11:06
I think this is a duplicate of #79

I haven't looked into that closely yet so i can't say much. But for now closing as duplicate, feel free to reopen if you believe this is a different issue.

**Closed by lawl** 2021-03-11 11:06 UTC
